### ISSUE TITLE
avy-goto-char-2 can't be used?

### ISSUE THREAD

**Issue by andyque** [cute-jumper/ace-pinyin#2]
When setting `(setq ace-pinyin-use-avy t)`, the `avy-goto-char-2` is not supported.

**Comment by cute-jumper** [comment]
Yep. Currently `ace-pinyin` only supports `ace-jump-char-mode` and `avy-goto-char`. However, `avy-goto-char-2` can be easily added. You could submit a pull request, or I could find some time to implement it.:-)

**Comment by cute-jumper** [comment]
Hi, I pushed new commits which added support for `avy-goto-char-2`(see the newest version on GitHub). I just did a very quick hack and didn't get too much time to test the new version yet. Feedback is very welcome!

**Comment by cute-jumper** [comment]
@andyque I'm closing this issue now because it seems that the newly added `avy-goto-char-2` works fine. If you find any problems, feel free to reopen this issue.:-)
