### ISSUE TITLE
call (ace-pinyin-global-mode) twice will issue error "Ace-pinyin mode has already been turned on."

### ISSUE THREAD

**Issue by andyque** [cute-jumper/ace-pinyin#3]

**Comment by cute-jumper** [comment]
How do you call this function? I can imagine some cases in which this can happen.

**Comment by andyque** [comment]
@cute-jumper  I call `SPC f e R` in spacemacs. It will automatically reload all the configurations. And now the `ace-pinyin-global-mode` would be call twice. I think you should issue error here. 
In other modes, we could also call a function more than twice.

**Comment by cute-jumper** [comment]
Make sense. Fix it in https://github.com/cute-jumper/ace-pinyin/commit/a70db348d60fe20570d8f160e9c0b81e0b1b1938.

**Comment by andyque** [comment]
@cute-jumper  :+1:
