### ISSUE TITLE
not working on some characters

### ISSUE THREAD

**Issue by Kejia** [cute-jumper/ace-pinyin#4]
i am using emacs 25.0.50.1 on macbook. it seems ace-pinyin doesn't work on some characters, such as 'i' and 'u'.

**Comment by cute-jumper** [comment]
OK. It seems this is a bug and should have been fixed in https://github.com/cute-jumper/ace-pinyin/commit/cfd6d9eb47f74f6fef47d0ebe90ae826234b4ae7. Try the new version and see if it works.

**Comment by Kejia** [comment]
i tested the latest code on both osx and linux: now it works well. thanks a lot.

**Comment by cute-jumper** [comment]
Thanks
