### ISSUE TITLE
Make mode-line lighter optional

### ISSUE THREAD

**Issue by girzel** [cute-jumper/ace-pinyin#8]
I like this mode, but don't really need "AcePY" in the mode line. Please consider making an ace-pinyin-lighter option that we can set to nil if we want.

Thanks!

**Comment by cute-jumper** [comment]
You can disable the lighter using `diminish.el`. If you don't want to install `diminish.el`, you can use the code below (extracted from `diminish.el`):

```
(let ((minor (assq 'ace-pinyin-mode minor-mode-alist)))
  (setcdr minor (list "")))
```

**Comment by girzel** [comment]
Will do, thanks.
